apiVersion: v1
kind: Service
metadata:
  name: vendo-svc
  namespace: nginx-test
spec:
  type: ClusterIP
  selector:
    app: vendo-web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: cozy86-svc
  namespace: nginx-test
spec:
  type: ClusterIP
  selector:
    app: cozy86-web
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
